using `vtctl` in docker got an undesired syslog error, which is actually benign, but using `--vtctld` option should avoid this nicely
Summary:
the error doesn't affect the actual stdout result we expecting, but as we check the return code, it doesn't look at the stdout at all
```
ERROR: logging before flag.Parse: E0222 19:43:42.247060     522 syslogger.go:122] can't connect to syslog
W0222 19:43:42.251638     522 vtctl.go:80] cannot connect to syslog: Unix syslog delivery error
```
and if we use the `vtctlclient -server` we won't get the same error:
```
sudo docker exec -ti vtctld /vt/bin/vtctlclient -server localhost:15991 GetShard patiogeneral/0
{
  "master_alias": {
    "cell": "test",
    "uid": 1024
  },
  "key_range": null,
  "served_types": [
    {
      "tablet_type": 1,
      "cells": [
      ]
    },
    {
      "tablet_type": 2,
      "cells": [
      ]
    },
    {
      "tablet_type": 3,
      "cells": [
      ]
    }
  ],
  "source_shards": [
  ],
  "cells": [
    "test"
  ],
  "tablet_controls": [
  ]
}
```

Reviewers: #vitess, epruitt, sreshtav

Reviewed By: #vitess, sreshtav

Subscribers: jenkins

Differential Revision: https://phabricator.pinadmin.com/D367551